apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
spec:
  groups:
  - name: node.rules
    rules:
    - alert: NodeHighCPU
      expr: instance:node_cpu_utilisation:rate5m > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        description: "CPU usage on {{ $labels.instance }} is above 80%"
        runbook_url: "https://runbooks.mecan.ata.tips/node-high-cpu.html"

    - alert: NodeMemoryFull
      expr: instance:node_memory_utilisation:rate5m > 0.85
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "Memory usage on {{ $labels.instance }} is above 85%"

  - name: kubernetes.rules
    rules:
    - alert: KubePodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"

    - alert: KubePersistentVolumeFull
      expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes < 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "PV {{ $labels.persistentvolume }} is nearly full" 