all:
  children:
    jump_server:
      hosts:
        jump-01:
          ansible_host: "{{ jump_server_ip }}"
    
    k8s_masters:
      hosts:
        master-1:
          ansible_host: "{{ master_1_ip }}"
        master-2:
          ansible_host: "{{ master_2_ip }}"
        master-3:
          ansible_host: "{{ master_3_ip }}"
    
    k8s_workers:
      hosts:
        worker-1:
          ansible_host: "{{ worker_1_ip }}"
        worker-2:
          ansible_host: "{{ worker_2_ip }}"
        worker-3:
          ansible_host: "{{ worker_3_ip }}"
    
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ playbook_dir }}/../files/ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no - 