loki:
  auth_enabled: true
  storage:
    type: s3
    s3:
      s3: s3://loki-logs
      region: us-west-2
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  limits_config:
    retention_period: 30d
  ruler:
    storage:
      type: s3
      s3:
        bucket_name: loki-rules
  compactor:
    retention_enabled: true
  replicaCount: 2

promtail:
  config:
    snippets:
      extraRelabelConfigs:
        - action: replace
          source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node_name
    clients:
      - url: http://loki:3100/loki/api/v1/push