# Velero backup configuration
velero:
  configuration:
    provider: aws
    backupStorageLocation:
      name: aws
      bucket: mecan-k8s-backups
      config:
        region: us-west-2
    volumeSnapshotLocation:
      name: aws
      config:
        region: us-west-2
    
  schedules:
    daily-backup:
      schedule: "0 1 * * *"
      template:
        ttl: "720h"
        includedNamespaces:
          - "*"
        excludedNamespaces:
          - kube-system
        includeClusterResources: true
        
  credentials:
    secretContents:
      cloud: |
        [default]
        aws_access_key_id=${AWS_ACCESS_KEY_ID}
        aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  backupStorageLocation:
    provider: aws
    bucket: my-backup-bucket