apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  resources:
  - group: ""
    resources: ["pods", "services"]
- level: RequestResponse
  resources:
  - group: ""
    resources: ["secrets", "configmaps"]
  omitStages:
  - RequestReceived
- level: Request
  users: ["system:admin"]
  resources:
  - group: ""
    resources: ["pods/exec", "pods/attach"] 