apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: kafka
    targetRevision: 22.1.3
    helm:
      values: |
        replicaCount: 3
        persistence:
          enabled: true
          size: 20Gi
        metrics:
          kafka:
            enabled: true
          jmx:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
