apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mongodb
    targetRevision: 13.6.0
    helm:
      values: |
        architecture: replicaset
        replicaCount: 3
        auth:
          enabled: true
          existingSecret: mongodb-creds
        persistence:
          enabled: true
          size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
